on:
  push:
    paths-ignore:
      - ".github/workflows/lighthouse.yml"
      - "lighthouse.js"
    branches:
      - 'main'

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build & Deploy
        run: |
          npm install
          npm build

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: build/

  lighthouse-report:
    needs: build-and-deploy
    uses: ./.github/workflows/lighthouse.yml